name: build

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master, test-ci ]
  pull_request:
    branches:
      - 'master'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    runs-on: ubuntu-latest

    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    - name: Install gcc 9
      run: sudo apt-get install gcc-9

    - name: Build with CMake
      run: |
        cmake -B build -DCMAKE_C_COMPILER=$(which gcc-9) -DCMAKE_CXX_COMPILER=$(which g++-9) -DCMAKE_BUILD_TYPE=Release .
        make -C build -j8

  windows-build:
    runs-on: [windows-latest]
    steps:
    - uses: actions/checkout@v2
    - name: Build on Windows
      run: |
        cmake -T "ClangCl" --config Release -B build .
        cmake --build build
